checksumBehavior: update

compressionLevel: mixed

conditions:
  USE_SRC:
    default: false

enableColors: true

enableGlobalCache: false

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.com/"
npmRegistryServer: "https://registry.npmjs.org/"
npmAuthToken: "${NPM_AUTH_TOKEN}"


plugins:
  - checksum: 40e072a2f71bd4638ee0f69f2d974477732f5e1c64b786b8f09b296d39cda7cbf503f355c6843e11f95480ae926009b0f6aa46b5a43821c3e005c9ef81c4ad57
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.5.0/bundles/@yarnpkg/plugin-after-install.js"
  - path: .yarn/plugins/@yarnpkg/plugin-conditions.cjs
    spec: "https://raw.githubusercontent.com/nicolo-ribaudo/yarn-plugin-conditions/main/bundles/%40yarnpkg/plugin-conditions.js"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
